### ISSUE TITLE
Undefined RFC 6962 test vector

### ISSUE THREAD

**Issue by rozbb** [transparency-dev/merkle#40]
This is a small point, but Merkle consistency proofs are not defined for `m == n`. From [section 2.1.2](https://datatracker.ietf.org/doc/html/rfc6962#section-2.1.2):

> Given an ordered list of n inputs to the tree, `D[n] = {d(0), ..., d(n-1)}`, the Merkle consistency proof `PROOF(m, D[n])` for a previous Merkle Tree Hash `MTH(D[0:m])`, `0 < m < n`, is defined as:
> ```
> PROOF(m, D[n]) = SUBPROOF(m, D[n], true)
> ```

Since the case of `m == n` is undefined, [this test vector](https://github.com/transparency-dev/merkle/blob/f5e1dc52b3453b76c726c9e7438f25d8da4aef01/testonly/reference_test.go#L171) should probably be deleted. Also, [`refConsistencyProof()`](https://github.com/transparency-dev/merkle/blob/f5e1dc52b3453b76c726c9e7438f25d8da4aef01/testonly/reference_test.go#L71) is defined with the wrong bounds. It is the case that, while the top-level `PROOF` is not defined for `m == n`, `SUBPROOF` is. A separate helper function is probably necessary here.

**Comment by AlCutter** [comment]
Hi rozbb, many thanks for taking the time to file the issue, and apologies for the huge delay in responding.

While you're right that this is an undefined case, given that this is a library we thought it better to have a stable (and non-fatal) response when it does occur - so perhaps this particular test case is best thought of in that framing, rather than one of ensuring formal correctness.
